### ISSUE TITLE
Add option to mass delete entries.

### ISSUE THREAD

**Issue by ccuser44** [jlwitthuhn/OpenCloudTools#1]
Add an option to mass delete entries. Also mark deleted entries as deleted in the key explorer (And add a possible option to hide them). Also make switching Datastores in the menu switch the entries menu as well.

Preferrably allow selecting multiple entries and allow the "Delete entry" button function on all of the selected entries.

Preferrably also allow a "Delete datastore" button, which clears all of the entries under it.

**Comment by jlwitthuhn** [comment]
Will take a look and see what I can do here.

Everything except showing which entries are deleted in the list view seems doable. Unfortunately that can't be done because the 'list keys' API doesn't distinguish between deleted and alive keys without querying each key individually, which would be too slow to be practical.

**Comment by jlwitthuhn** [comment]
Delayed update here, bulk delete was added in commit 84ab545f45f4c0806a92ea201791fcfb9f89bdf4 which was included in the last two releases.

Still need to support deleting multiple selected keys in the main datastore view.

**Comment by jlwitthuhn** [comment]
With commit 2246d74e4f52487419b9ed7288f8e6c492694157 it is now possible to select multiple entries in the list and delete them all with one button.

This hasn't been released yet, but will be included in the next release. Will close this issue at that time.
