### ISSUE TITLE
App throwing a 403

### ISSUE THREAD

**Issue by Asynchronite** [jlwitthuhn/OpenCloudTools#4]
Before I start, I'd say that this is more of a roblox error than anything but here goes.
Whenever I try to fetch datastores from a group game (I made a master API key, meaning I granted it all scopes), the app throws a 403 error saying I don't have the necessary scopes:
`Received HTTP 403, aborting
{"error":"INSUFFICIENT_SCOPE","message":"Insufficient scope to perform the operation.","errorDetails":[{"errorDetailType":"DatastoreErrorInfo","datastoreErrorCode":"InsufficientScope"}]}`

**Comment by Asynchronite** [comment]
For context, this error is thrown when I click the "Fetch datastores" button.

**Comment by icrann** [comment]
Are you sure you are matching the correct game(s) with the API Key? Also there are different datastores APIs as you can see here:
![image](https://github.com/user-attachments/assets/b14d1e78-c7a4-48ed-9ff8-a94176d630b3)

**Comment by Asynchronite** [comment]
I only have `ordered-data-stores` and `universe-datastores`.
As for the universe ID, I've copied it from the creator dashboard but I've also grabbed it from the page source. It is 100% the correct one.

**Comment by jlwitthuhn** [comment]
Hey, thanks for reporting. Apologies for not responding faster, I don't check the issues here very often.

I'm not able to reproduce this problem for my own group-owned game so I have some thoughts here.

Make sure you have the right permission for `universes-datastores`. The one you need to make "Fetch datastores" work is `universe-datastores.control:list`. Make sure you have that one, not to be confused with `universe-datastores.objects:list` or `universe-datastores.versions:list` which are separate permissions. The one you want is in the bottom section of the list.

I made a minimal key here with only this permission for a group-owned game and I was able to "Fetch datastores" without a problem.
![image](https://github.com/user-attachments/assets/c63e5127-0e59-4ece-83a8-3460f498f617)

I'll also make a point to update the README soon. The language on the key creation site has changed since I wrote it so it isn't clear exactly what is needed now. I'll update it to use the new permission names wherever that is relevant.

**Comment by Asynchronite** [comment]
Alright.
I removed my old key and made a new one, and it seems to work now, so I'm assuming it was either a temporary roblox change that they didn't announce or I seemingly forgot to enable a scope on the key.
In any case, thanks for the time, and I'm looking forward to an updated README :D
